added first draft of broker API spec
DFE-Digital/teacher-id pull request #4
Opened 2021-11-24 16:50 UTC by dendle

# TeacherID Broker API - OpenAPI spec draft

As part of the TeacherID system, the TeacherID - Broker API is intended to be used by calling systems to query datasets in DfE to find related identifiers, so that they can use the data they already have about a user to discover other data in other services related to the same user.

There are 2 main endpoints:
1. Find
  This endpoint is used to discover other attributes related to a user, given the attributes that the caller already has.  For example, a service might query for a TRN related to an email address - or might query if we hold a NINO for a given TRN etc.
2. Associate
  This endpoint is used to allow services to share information they learn about their users with other services.  In this case, if a service learns of an association between an email address and a TRN for example, this endpoint is used to share that association, and make it available for other services.

2021-11-25 11:21 UTC, aje54 requested changes
please change to be OAS 3.0 spec. Using components for data objects https://swagger.io/docs/specification/components/

2021-11-29 10:08 UTC, dendle commented
@aje54 Spec version updated to 3.0.3

2021-11-29 15:03 UTC, dendle commented
Going to park the Broker API for now, in order to focus on FindMyTRN service

2021-12-02 15:35 UTC, aje54 approved these changes

2021-12-09 10:18 UTC, closed without merging